/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrackRouteImport } from './routes/api/track'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'

const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/metricas': typeof MetricasRoute
  '/obrigado': typeof ObrigadoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/track': typeof ApiTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metricas': typeof MetricasRoute
  '/obrigado': typeof ObrigadoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/track': typeof ApiTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/metricas': typeof MetricasRoute
  '/obrigado': typeof ObrigadoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/track': typeof ApiTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/metricas'
    | '/obrigado'
    | '/politica-de-privacidade'
    | '/api/leads'
    | '/api/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/metricas'
    | '/obrigado'
    | '/politica-de-privacidade'
    | '/api/leads'
    | '/api/track'
  id:
    | '__root__'
    | '/'
    | '/metricas'
    | '/obrigado'
    | '/politica-de-privacidade'
    | '/api/leads'
    | '/api/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetricasRoute: typeof MetricasRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiTrackRoute: typeof ApiTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetricasRoute: MetricasRoute,
  ObrigadoRoute: ObrigadoRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiTrackRoute: ApiTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
